config-version: 2

opening:
  animation-ticks: 120
  roulette-interval-ticks: 4

interaction:
  preview-on-left-click: true
  open-on-right-click: true
  target-distance: 6

history:
  enabled: true

editor:
  title: "&5MiraCrates Editor"
